spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo_password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false